# Site settings
title: RASE 2026 Challenge
email:
description: >-
  Radar Acoustic Speech Enhancement Challenge @ ICASSP 2026. Recover speech from mmWave radar through glass. Dataset, baselines, and rules inside.
twitter_username: username
github_username: username

# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint
search: false   # hide search icon/site search

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: null
timezone:

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: ""
  avatar:
  bio: ""
  links: []

footer:
  links: []

# Defaults
defaults:
  # posts (unused here, but kept harmless)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      toc: false

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
